name: Publish VS Code Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/vscode/**'

jobs:
  publish:
    if: github.repository_owner == 'timothymiller'
    name: Publish VS Code Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Check version changes
      #   uses: EndBug/version-check@v1
      #   id: check
      #   with:
      #     file-name: ./apps/vscode/package.json

      # - name: Version update detected
      #   if: steps.check.outputs.changed == 'true'
      #   run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Setup Node.js for NPM
        # if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ“¥ Monorepo install
        # if: steps.check.outputs.changed == 'true'
        uses: ./.github/actions/bun-install

      - name: Publish
        # if: steps.check.outputs.changed == 'true'
        run: cd apps/vscode && bun dlx @vscode/vsce publish --no-dependencies -p ${{ secrets.VSCE_TOKEN }}
